# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  workflow_dispatch:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows] # 需要打包的系统
        goarch: [amd64, arm64] # 需要打包的架构
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.50
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "libre-sealdice-core" # 可以指定二进制文件的名称
          pre_command: "go mod tidy && go generate ./..."
          release_tag: Pre-release
          overwrite: true
          asset_name: libre-sealdice-core-${{ matrix.goos }}-${{ matrix.goarch }}
          md5sum: false
          extra_files: README.md LICENSE